### ISSUE TITLE
Why it does not get update?

### ISSUE THREAD

**Issue by ghost** [Alex313031/Thorium-Linux-AVX2#1]
windows version is 119 but it is 115 why?

**Comment by crepassob** [comment]
The Linux avx2 version is here [Thorium-Other](https://github.com/Alex313031/Thorium-Other/releases/tag/119.0.6045.214)

**Comment by ghost** [comment]
@crepassob Ah i see but already we have seperate repo for it why its on other repo?

**Comment by crepassob** [comment]
I don`t know it.I think this version is a simple build and not add or fix somethings.So put it other repo.

**Comment by Alex313031** [comment]
@toprak @crepassob Honestly forgot that I made this repo.
I put it in other since it was a gift. I will publish it here as well.

UPDATE: Here y'all go : https://github.com/Alex313031/Thorium-Linux-AVX2/releases/tag/M119.0.6045.214

**Comment by Alex313031** [comment]
@toprak @crepassob M120 > https://github.com/Alex313031/Thorium-Linux-AVX2/releases/tag/M120.0.6099.276
