### ISSUE TITLE
Latest AppImage version closes unexpectedly with "bus error" message

### ISSUE THREAD

**Issue by Jarmund5** [Alex313031/Thorium-Linux-AVX2#2]
As the title says, browser closes unexpectedly after startup (roughly a minute in) no matter what i do. But i can make it crash _faster_ if i try load a very heavy website like youtube. Open in it up in a terminal, it throws the "bus error" message when it crashes.

**I have no extensions installed nor any flags changed**

My system is:
```
Debian 12 with KDE Plasma 5.27.5
Intel Core i3-6006U with 4GB of RAM
```
PD: If it's worth something, i use the X11 session of Plasma, but crashes all the same in the Wayland session.

**Comment by Alex313031** [comment]
@Jarmund5 Can you test with latest release? ALso if issue persists, file this same bug in the main repo, as I am deprecating this repo as per the latest releases here. > https://github.com/Alex313031/Thorium-Linux-AVX2/releases/tag/M121
